### ISSUE TITLE
bundle winetricks

### ISSUE THREAD

**Issue by philipzae** [probonopd/libhookexecv#10]
Bundling winetricks make it possible to do more with the proton appimage.

Saw the foobar2000 appimage would download the winetricks
https://github.com/mmtrt/foobar2000_AppImage/blob/master/AppRun#L102

**Comment by probonopd** [comment]
As per the AppImage philosophy, it should not be downloaded at runtime, but should be bundled inside the AppImage. Would you like to send a PR?

**Comment by philipzae** [comment]
I gave it a try https://github.com/probonopd/libhookexecv/pull/12

**Comment by probonopd** [comment]
Thanks, it is almost working but needs some bash scripting.

**Comment by probonopd** [comment]
Seems to be working, at least doing something, see #22 for an example. Thank you very much :+1:
