### ISSUE TITLE
bundle ms core fonts

### ISSUE THREAD

**Issue by philipzae** [probonopd/libhookexecv#14]
I think the most important ms fonts (arial, courier, times, verdana) should be bundled with the appimage, as some apps wont work without them. Wine already bundles tahoma and wingding.

I have the pull request prepared, but wondered if i should put them in
./Wine.AppDir/usr/share/fonts/truetype/msttcorefonts

**Comment by probonopd** [comment]
I think they are not allowed to be redistributed as part of an application bundle, but I may be wrong. Have you checked the licensing?

**Comment by philipzae** [comment]
Haven't checked the licensing but the ubuntu package requires the download of the fonts and agreeing to a EULA. - https://i.stack.imgur.com/3T0Jb.png

**Comment by probonopd** [comment]
Does not sound good to me.

**Comment by philipzae** [comment]
winetricks and playonlinux install them without prompting about a EULA, but i guess with winetricks in the appimage, people could easily install it that way anyway.

**Comment by philipzae** [comment]
If things change and its wanted to do so, then here was the code i was planning to submit as a patch.

```
mkdir -p ./Wine.AppDir/share/wine/fonts/msttcorefonts

wget "http://downloads.sourceforge.net/corefonts/arial32.exe" && cabextract -F *.ttf -d "./Wine.AppDir/usr/share/fonts/truetype/msttcorefonts" arial32.exe
wget "http://downloads.sourceforge.net/corefonts/courie32.exe" && cabextract -F *.ttf -d "./Wine.AppDir/usr/share/fonts/truetype/msttcorefonts" courie32.exe
wget "http://downloads.sourceforge.net/corefonts/times32.exe" && cabextract -F *.ttf -d "./Wine.AppDir/usr/share/fonts/truetype/msttcorefonts" times32.exe
wget "http://downloads.sourceforge.net/corefonts/verdan32.exe" && cabextract -F *.ttf -d "./Wine.AppDir/usr/share/fonts/truetype/msttcorefonts" verdan32.exe
```

**Comment by probonopd** [comment]
Now that we have winetricks I think it can handle that.
