### ISSUE TITLE
Ignoring locally installed Wine

### ISSUE THREAD

**Issue by roos-robert** [probonopd/libhookexecv#23]
Hi!

I'm a beginner at this and could use some pointers on how to get started. :)
I've done the following and it's working great

```
wget -c https://github.com/probonopd/libhookexecv/releases/download/continuous/Wine_Windows_Program_Loader-3.5-x86_64.AppImage

chmod +x Wine*.AppImage

wget -c https://github.com/probonopd/libhookexecv/releases/download/continuous/wineprefix.tar.gz
tar xf wineprefix.tar.gz

WINEPREFIX=$(readlink -f wineprefix) ./Wine_Windows_Program_Loader-3.5-x86_64.AppImage notepad++
```

Next I've extracted the AppImage to add another application into it, but this is where I'm getting stuck. On trying to run for example `./squashfs-root/AppRun winetricks` the locally installed winetricks is triggered and started, the same if trying to call "wine".

Is there a way to ignore the locally installed version of Wine (using it for games etc.), and only use the Wine version from the AppImage? So that I can use e.g. Winetricks to install .NET and other deps for the app I'm trying to add.

Thanks in advance!

**Comment by probonopd** [comment]
It _should_ already be that way (it should always prefer the Wine from inside the AppDir/AppImage). What happens if you run `./squashfs-root/AppRun Some.exe`?

Maybe you can find out how `winetricks` finds Wine by looking at its source/documentation, I don't remember.

**Comment by probonopd** [comment]
`winetricks` always uses the wine and `wineserver` that is on the `$PATH`. So you need to symlink the WINE AppImage to e.g., `/usr/local/bin/wine` and `/usr/local/bin/wineserver`. When you invoke `winetricks` then, it should use the WINE from the AppImage.

Please report back whether this works.

Alternatively, it may work by setting `$WINESERVER` and `$WINE` and then invoking `winetricks` as mentioned by @ferion11.

Reference:
https://github.com/ferion11/Proton_Appimage/issues/1

**Comment by ferion11** [comment]
If setting $WINESERVER and $WINE don't work, then you can just use local variables to put it on the PATH to work only inside the script. Like:
```
#!/bin/bash
APPDIR_BIN="/tmp/.tmp_bin_test_if_i_have_write_access_first"
mkdir -p "$APPDIR_BIN"
export PATH=$APPDIR_BIN:$PATH

ln -s wine.Appimage "$APPDIR_BIN/wine"
ln -s wine.Appimage "$APPDIR_BIN/wineserver"

env WINEPREFIX=~/.proton32 sh ./winetricks

rm -rf "$APPDIR_BIN"
```
This is useful if the script don't support the variables and you don't want to change the default of your system.
